### ISSUE TITLE
Add support to append dot behind the record.

### ISSUE THREAD

**Issue by tuapuikia** [barnybug/cli53#124]
The current export do not include (dot) behind the record. This will caused the record to be resolved as xxx.amazon.aws.com.($ORIGIN domain).

Below is output using export command.
$ORIGIN testing.com
xx
xx
production 120 IN CNAME ec2-11-11-11-11.compute-1.amazonaws.com

dig production.testing.com will return ec2-11-11-11-11.compute-1.amazonaws.com.testing.com 

because there is no (dot) behind the record by default. 

So far it only affect CNAME record. A record return the result correctly.

**Comment by barnybug** [comment]
Hi, the issue you are seeing is (probably) because you've created the domain without a trailing dot, you must include this, otherwise you are creating it relative. eg (note '.' after final .com):
cli53 rrcreate testing.com 'production CNAME ec2-11-11-11-11.compute-1.amazonaws.com.'

Or if you're importing the same rules around qualification apply, but some providers export broken zone files: https://github.com/barnybug/cli53/#broken-cname-exports-godaddy

Does that help resolve?

**Comment by tuapuikia** [comment]
Thanks for the 1 line fixer. It working very well.
