### ISSUE TITLE
not fair to have removed it from pip

### ISSUE THREAD

**Issue by lra** [barnybug/cli53#128]
Our production system relied on it, now we have to hotfix it ;)

Just FYI.

**Comment by lra** [comment]
just noticed https://github.com/barnybug/cli53#wheres-pythonpypi-cli53 thx to @jbz

**Comment by barnybug** [comment]
Hi, it's unfortunate this happened. As you found in the explanation in the README - my reasoning is because of the support effort for an old version and python cli53 had a number of bugs and limitations that weren't readily solveable.

People blindly following instructions elsewhere on the internet to 'pip install cli53' just led to them recurring. The old version poorly represented the project, as well as being cumbersome to install on some dists.

Just a word of advice: you'd be better having your production system not relying on an external service like pypi for a couple of very good reasons. Firstly, whilst it's improved it a lot recently, pypi particularly has a chequered history in terms of uptime and reliability. Secondly, third party software (without hashes/a verification chain) could be installing *anything* onto your system. As an example, rubygems was compromised not long ago. As good security practice, I'd always install to prd from a private mirror you've independently verified, this would also solve the problem with versions disappearing. :-)

Please spare a thought for the effort developers put into open sourcing and supporting open source projects too.
