### ISSUE TITLE
Suggest to take over the maintenance of PyPI cli53

### ISSUE THREAD

**Issue by annguyenfoss** [barnybug/cli53#134]
Hello good sir - I don't know why you dropped Python but I still have a lot of interests in your good old codebase. Therefore, I would like to request for your permission to take over the maintenance of PyPI cli53. I will certainly comply with any authorship & licensing requirements from you.

Please let me know.
Regards.
An.

**Comment by barnybug** [comment]
Hi, perhaps if I explain the reasoning behind the rewrite it might help understand the difficult decisions I've been faced.

The main problem with cli53 going forward was it is based on the boto library, which seems to have stagnated in development. Without good support from the main library it depends on, it's going to be hard work to maintain cli53. The main areas of pain are around the new route53 features - there were tickets for functionality we required that had been sat for months.

Rewriting it to use the AWS supported library boto3 would have been a significant undertaking.

The second problem with cli53 was the ALIAS functionality was, to put it bluntly, totally broken. It was contributed by someone a bit ill-conceived and I hadn't the time/didn't realise when it was first merged that was the case. For example, it wouldn't handle anything other than A records.

Additionally cli53 was missing a lot of the extra functionality route53 has over normal DNS (geo records, region latency routing, etc).

I couldn't see a workable transition to python 3 either, and didn't want to stall this forever.

Looking at the options, golang made a lot more sense to me now for command line tools - single executable, much more manageable dependencies. The golang version has received positive feedback from first users. But even having hidden cli53 from visibility in pypi, I was still getting tickets for the old cli53 requesting fixes. It took me a while to figure out, it's simply because the instructions 'pip install cli53' are out there now, and people don't tend to read further than running a command blindly, and if that doesn't work they file a ticket!

So it left me a support burden of either running a concurrent version (madness), or I take cli53 off pypi completely. Unfortunately this has bitten a couple of people - which is regrettable.
My take would be that production systems should always install from your own pip private repo (they're so easy to setup - drop the zips on s3) and really shouldn't be installing from pypi - it's not guaranteed to be up and it's not secured, so any old code could be going on if a version was replaced maliciously. (This is not a hypothetical situation - it happened with ruby gems!).

Anyway - enough rambling. The issue remaining is how to avoid being to encumbered by the legacy of support for the previous cli53, still allow people needing the old version to pip install it, and also to point them to the new version without them having to go read the README (which no one seems to do!), or file a ticket.

I think the best action is I put back up the last release for installation on pypi, but including a notification it's been end of life.

Welcome to suggestions, but I don't think trying to maintain cli53 python as the last version is reasonable or would represent the project well either.

**Comment by barnybug** [comment]
Have gone ahead with this plan - cli53 0.5.2.

**Comment by annguyenfoss** [comment]
Thank you very much for your clarification. I highly appreciate your tool and your response. 

I can see that your last version of python cli53 is on PyPI now, https://pypi.python.org/pypi/cli53. I'm taking down my fork to avoid confusion.

Cheers.
An.
